exclude: ["*.old"]

baseurl: ''

sass:
    style: compressed

defaults:
  -
    scope:
      type: "pages"
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"