exclude: ["*.old"]

#plugins:
#  - jekyll-font-awesome-sass

sass:
    sass_dir: _sass
    style: nested

defaults:
  -
    scope:
      type: "pages"
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"