exclude: ["*.old"]

plugins:
  - jekyll-font-awesome-sass

defaults:
  -
    scope:
      type: "pages"
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"